name: ai_voice_chat
description: AI voice + text chat app (Whisper + GPT + TTS)
publish_to: "none"
version: 1.0.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  dio: ^5.4.0
  flutter_chat_ui: ^1.6.9
  flutter_chat_types: ^3.4.0
  record: ^4.4.4
  web_socket_channel: ^2.4.0
  just_audio: ^0.9.36
  path_provider: ^2.0.14
  vad: 
  uuid: ^3.0.7
  flutter_webrtc: ^0.11.7
  flutter_sound: ^9.2.13
  flutter_sound_platform_interface: ^9.2.13
  http: ^0.13.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
